version: 2
updates:
- package-ecosystem: cargo
  directory: "/ci"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 1
  groups:
    cargo-dependencies:
      patterns:
        - "*"
    cargo-security-updates:
      applies-to: security-updates
      patterns:
        - "*"
